baseurl: /MaptimeStateCollege
permalink: pretty
markdown: kramdown
paginate: 5
repo: starter
github_org: maptime
maptime:
  chapter: Maptime State College
  twitter: MaptimeState
  #disqus: YOUR DISQUS USERNAME
